"""Graph backend protocol."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class GraphBackend(Protocol):
    """Protocol for graph storage backends."""

    def add_node(self, name: str, **attrs: Any) -> None: ...
    def remove_node(self, name: str) -> None: ...
    def has_node(self, name: str) -> bool: ...
    def add_edge(self, source: str, target: str, **attrs: Any) -> None: ...
    def remove_edge(self, source: str, target: str) -> None: ...
    def get_children(self, name: str) -> list[str]: ...
    def get_ancestors(self, name: str) -> list[str]: ...
    def get_nodes(self) -> list[str]: ...
    def get_edges(self) -> list[tuple[str, str, dict]]: ...
    def to_dict(self) -> dict: ...
    def from_dict(self, data: dict) -> None: ...
